name: バグフィードバック
description: バグの報告
title: "[Bug] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        問題を送信する前に、次のことを確認してください。:
        + 同じ問題は以前には存在しませんでした 
        + このバグは WordPress プラグインやブラウザ プラグインによって引き起こされるものではありません 
        + このバグはテーマが原因で発生します (他のテーマでは再現できません)
  - type: input
    id: theme-version
    attributes:
      label: テーマバージョン
      description: バグが発生したテーマのバージョン (またはバグが最初に発生したテーマのバージョン)
      placeholder: "v1.0.0"
    validations:
      required: true
  - type: dropdown
    id: issue-type
    attributes:
      label: Bugの種類
      options:
        - バグはバックエンドの問題です 
        - このバグはフロントエンドの問題であり、ブラウザとは関係ないようです 
        - このバグはフロントエンドの問題ですが、特定のブラウザでのみ発生します 
        - バグの種類を特定できません
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: ブラウザ
      description: このバグはどのブラウザで発生しますか?
      options:
        - Chrome / Edge
        - Firefox
        - Safari
        - Other
        - この問題はフロントエンドとは関係ありません
    validations:
      required: true
      
  - type: dropdown
    id: is-universal-issue
    attributes:
      label: 普遍性
      description: このバグは Argon テーマを使用しているすべての Web サイトで発生しますか?
      options:
        - はい 
        - いいえ、特定の Web サイトにのみ表示され、トリガー条件を知っています 
        - いいえ、特定の Web サイトにのみ表示されますが、発生条件は不明です
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 問題の説明
      description: このバグはどの機能に関するものですか？どのような問題がありますか？
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 再現手順
      description: このバグは再現可能ですか?再現方法は？
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: スクリーンショット
      description: スクリーンショットを追加すると、問題をより明確に説明できます。
      value: 
  - type: textarea
    id: other
    attributes:
      label: 追加情報
      description: ここに追加の手順を追加します。
