name: 機能リクエスト
description: 新しいFeatureを提案する
title: "[Feature Request] ここにタイトルを入力してください"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        問題を送信する前に、次のことを確認してください。
        + 同じ問題は以前には存在しませんでした
        + この機能はテーマに関連しています
  - type: textarea
    id: description
    attributes:
      label: 機能説明
      description: 新しい機能とその機能について説明する
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 追加情報
      description: ここに追加の説明を追加します。
