name: その他のカテゴリー
description: その他のカテゴリーでIssueを立てる
body:
  - type: markdown
    attributes:
      value: |
        問題を送信する前に、次のことを確認してください。:
        + 同じ問題は以前には存在しませんでした 
        + この問題は バグのフィードバックや feature リクエストに属していません。それ以外の場合は、上記のカテゴリを選択して送信してください 
        + 問題の内容を正確に説明する
  - type: textarea
    id: description
    attributes:
      label: Issue 内容
    validations:
      required: true
